// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TodoWebApi.Models
{
    public partial class Tasks
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Iscompleted { get; set; }
    }
}